In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import pandas_ta as ta

from gplearn.extra_functions_2 import *

from numpy.lib.stride_tricks import sliding_window_view

In [4]:
data = np.random.rand(4000, 300) 
data[::50] = np.nan
data

array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [0.14837244, 0.39225758, 0.88043431, ..., 0.9680262 , 0.00177419,
        0.57217006],
       [0.89474801, 0.97672314, 0.84095432, ..., 0.05394336, 0.48959762,
        0.21585114],
       ...,
       [0.2494453 , 0.91084856, 0.64784418, ..., 0.25025547, 0.59316832,
        0.79047461],
       [0.20735456, 0.26827509, 0.5824082 , ..., 0.30868677, 0.30025723,
        0.01137576],
       [0.34148375, 0.56099868, 0.5514481 , ..., 0.39275451, 0.86243566,
        0.79204902]])

In [5]:
dffct = pd.read_parquet('/home/pennymax/proj/MFM/CrossSection/v1_basic/basic_8h_2/fct_proc.parquet')

In [6]:
datafct = dffct.bckret5.unstack().to_numpy()
display(pd.DataFrame(datafct))

0    1         2         3         4         5         6    \
0          NaN  NaN       NaN       NaN       NaN       NaN       NaN   
1          NaN  NaN       NaN       NaN       NaN       NaN       NaN   
2          NaN  NaN       NaN       NaN       NaN       NaN       NaN   
3          NaN  NaN       NaN       NaN       NaN       NaN       NaN   
4          NaN  NaN       NaN       NaN       NaN       NaN       NaN   
...        ...  ...       ...       ...       ...       ...       ...   
3910 -0.103643  NaN -0.028451 -0.045687 -0.033122 -0.140934 -0.061677   
3911 -0.079608  NaN -0.008715  0.000734 -0.033769 -0.063728 -0.037235   
3912 -0.076490  NaN  0.007081  0.003673 -0.022267 -0.001847  0.000000   
3913 -0.018204  NaN  0.041000  0.056108  0.025714  0.089430  0.031868   
3914  0.006731  NaN  0.031793  0.023353  0.016487  0.053990  0.005733   

           7         8         9    ...       253       254       255  256  \
0          NaN       NaN       NaN  ... -0.032282       NaN       NaN  NaN   
1          NaN       NaN       NaN  ... -0.003044       NaN       NaN  NaN   
2          NaN       NaN       NaN  ... -0.014079       NaN       NaN  NaN   
3          NaN       NaN       NaN  ...  0.032346       NaN       NaN  NaN   
4          NaN       NaN       NaN  ...  0.022536       NaN       NaN  NaN   
...        ...       ...       ...  ...       ...       ...       ...  ...   
3910 -0.036430 -0.035449 -0.064911  ...  0.100000 -0.056712 -0.014335  NaN   
3911 -0.037437 -0.028726 -0.033326  ...  0.032860 -0.021861  0.000168  NaN   
3912 -0.029587 -0.017153 -0.032923  ... -0.030612  0.039559  0.003597  NaN   
3913  0.009718  0.020463  0.003694  ...  0.017040  0.055751  0.033370  NaN   
3914 -0.000930  0.002616 -0.003562  ... -0.035897  0.045233  0.007433  NaN   

           257       258       259       260       261       262  
0          NaN       NaN -0.006922       NaN       NaN       NaN  
1          NaN       NaN  0.001942       NaN       NaN       NaN  
2          NaN       NaN -0.014054       NaN       NaN       NaN  
3          NaN       NaN  0.027674       NaN       NaN       NaN  
4          NaN       NaN  0.025626       NaN       NaN       NaN  
...        ...       ...       ...       ...       ...       ...  
3910 -0.037909  0.033025 -0.015391 -0.049050 -0.026364 -0.017211  
3911 -0.026632  0.133534  0.004677 -0.027451 -0.015859 -0.020029  
3912 -0.022654  0.088710 -0.013086 -0.055348 -0.001356 -0.007282  
3913  0.013080  0.112760  0.031223 -0.020291  0.072368  0.024176  
3914 -0.001897  0.056891  0.000864 -0.038020  0.046512  0.003562  

[3915 rows x 263 columns]

In [16]:
%timeit ta_CMO(datafct, 14)

3.72 ms ± 6.98 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
%timeit pd.DataFrame(datafct).apply(ta.cmo, length=14).to_numpy()

10.8 ms ± 56.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
np.allclose(ta_CMO(datafct, 14), pd.DataFrame(datafct).apply(ta.cmo, length=14).to_numpy(), equal_nan=True)

True

In [25]:
# tszs_60_add(ts_mean_5(netbuyquo3), ta_BBANDSl_5_2_2(spot_Open))

netbuyquo3 = dffct.netbuyquo3.unstack().to_numpy()
spot_Open = dffct.spot_Open.unstack().to_numpy()

x1 = ts_mean(netbuyquo3, 5)
x2 = ta_BBANDSl(spot_Open, 5,5,2,0)
ret = tszs_add(x1, x2, 60)
pd.DataFrame(ret)


0    1         2         3         4    5    6         7    \
0          NaN  NaN       NaN       NaN       NaN  NaN  NaN       NaN   
1          NaN  NaN       NaN       NaN       NaN  NaN  NaN       NaN   
2          NaN  NaN       NaN       NaN       NaN  NaN  NaN       NaN   
3          NaN  NaN       NaN       NaN       NaN  NaN  NaN       NaN   
4          NaN  NaN       NaN       NaN       NaN  NaN  NaN       NaN   
...        ...  ...       ...       ...       ...  ...  ...       ...   
3910  1.201043  NaN  0.053036  0.107078  0.326916  NaN  NaN  0.265574   
3911  1.085945  NaN  0.108100  0.076111  0.028208  NaN  NaN  0.077193   
3912  0.984338  NaN  0.161373  0.091111 -0.128333  NaN  NaN -0.113998   
3913  0.944745  NaN  0.304039 -0.076997 -0.234581  NaN  NaN -0.098151   
3914  1.006638  NaN  0.519489 -0.326993 -0.071620  NaN  NaN  0.085752   

           8         9    ...       253       254       255  256       257  \
0          NaN       NaN  ...       NaN       NaN       NaN  NaN       NaN   
1          NaN       NaN  ...       NaN       NaN       NaN  NaN       NaN   
2          NaN       NaN  ...       NaN       NaN       NaN  NaN       NaN   
3          NaN       NaN  ...       NaN       NaN       NaN  NaN       NaN   
4          NaN       NaN  ...       NaN       NaN       NaN  NaN       NaN   
...        ...       ...  ...       ...       ...       ...  ...       ...   
3910  0.244867  1.874834  ...  2.877297  0.846889  1.188346  NaN  1.351317   
3911  0.090805  1.395174  ...  3.380551  0.695247  1.060694  NaN  1.116821   
3912 -0.148184  1.202009  ...  3.431515  0.716287  1.109504  NaN  1.018390   
3913 -0.377085  0.809893  ...  2.988648  0.803640  1.138776  NaN  1.241138   
3914 -0.520690  0.674682  ...  2.890672  0.945271  1.184413  NaN  1.284285   

           258       259       260       261       262  
0          NaN       NaN       NaN       NaN       NaN  
1          NaN       NaN       NaN       NaN       NaN  
2          NaN       NaN       NaN       NaN       NaN  
3          NaN       NaN       NaN       NaN       NaN  
4          NaN       NaN       NaN       NaN       NaN  
...        ...       ...       ...       ...       ...  
3910  2.031437  1.768750  0.657901 -0.171986  1.638280  
3911  1.936355  1.663987  0.666694 -0.366939  1.797745  
3912  1.756186  1.484775  0.682372 -0.396291  2.269082  
3913  2.169471  1.322816  1.020016 -0.555979  2.309762  
3914  2.872958  1.335675  0.808510 -0.671243  2.575563  

[3915 rows x 263 columns]

In [29]:
import numpy as np

def cs_zscore1(x):
    # 在计算过程中临时忽略特定警告
    with np.errstate(invalid='ignore', divide='ignore'):
        means = np.nanmean(x, axis=1, keepdims=True)
        stds = np.nanstd(x, axis=1, keepdims=True)

        z_scores = np.where(stds > 0, (x - means) / stds, 0)

    # 将原始 NaN 位置的值保持为 NaN
    z_scores[np.isnan(x)] = np.nan

    return z_scores

# 测试数据
x = np.array([
    [1, 2, np.nan, 4],
    [np.nan, np.nan, np.nan, np.nan],
    [7, 8, 9, 10]
])

print(cs_zscore(x))


[[-1.06904497 -0.26726124         nan  1.33630621]
 [        nan         nan         nan         nan]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]]


In [42]:
import numpy as np

def cs_zscore1(x):
    # 检查每行是否全部为 NaN
    all_nan_rows = np.isnan(x).all(axis=1)

    # 为非全 NaN 的行计算均值和标准差
    means = np.nanmean(x[~all_nan_rows], axis=1, keepdims=True)
    stds = np.nanstd(x[~all_nan_rows], axis=1, keepdims=True)

    # 初始化一个全为 NaN 的结果数组
    z_scores = np.full(x.shape, np.nan)

    # 只对非全 NaN 的行进行 Z-score 计算
    z_scores[~all_nan_rows] = (x[~all_nan_rows] - means) / stds

    # 将原始 NaN 位置的值保持为 NaN
    z_scores[np.isnan(x)] = np.nan

    return z_scores

# 测试数据
x = np.array([
    [1, 2, np.nan, 4],
    [np.nan, np.nan, np.nan, np.nan],
    [7, 8, 9, 10]
])

print(cs_zscore1(x))
np.allclose(cs_zscore1(datafct), cs_zscore1(datafct), equal_nan=True)


[[-1.06904497 -0.26726124         nan  1.33630621]
 [        nan         nan         nan         nan]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]]


True

In [44]:
np.nanmean(cs_zscore(datafct), axis=1).max()

8.017185735346263e-16

In [60]:
# 测试数据
x = np.array([
    [1, 2, np.nan, 4],
    # [np.nan, np.nan, np.nan, np.nan],
    [7, 8, 9, 10],
    [17, 18, 19, 110],
    [70, 80, -9, -10]
])
display(x)
dfx = pd.DataFrame(x)
display(dfx)
(dfx - dfx.rolling(2).mean())/dfx.rolling(2).std()

array([[  1.,   2.,  nan,   4.],
       [  7.,   8.,   9.,  10.],
       [ 17.,  18.,  19., 110.],
       [ 70.,  80.,  -9., -10.]])

0     1     2      3
0   1.0   2.0   NaN    4.0
1   7.0   8.0   9.0   10.0
2  17.0  18.0  19.0  110.0
3  70.0  80.0  -9.0  -10.0

0         1         2         3
0       NaN       NaN       NaN       NaN
1  0.707107  0.707107       NaN  0.707107
2  0.707107  0.707107  0.707107  0.707107
3  0.707107  0.707107 -0.707107 -0.707107

In [68]:
ts_zscore(x, 4)

array([[        nan,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan],
       [ 1.46677648,  1.47449944,         nan, -0.70030874]])

In [74]:
dfx[3][dfx[2].isna()] = np.nan
dfx

0     1     2      3
0   1.0   2.0   NaN    NaN
1   7.0   8.0   9.0   10.0
2  17.0  18.0  19.0  110.0
3  70.0  80.0  -9.0  -10.0

In [16]:
dff = pd.read_parquet('/home/pennymax/proj/MFM/CrossSection/v1_basic/basic_8h_2/fct_proc.parquet')
dff0 = dff.copy()
display(dff)
mask = dff.Close.isna()
dff.loc[mask, dff.columns != 'Close'] = np.nan
dff.equals(dff0)

Open       High        Low  \
time                      symbol                                      
2020-06-21 00:00:00+00:00 ADAUSDT     0.07941    0.08099    0.07924   
                          ATOMUSDT    2.62500    2.63100    2.59900   
                          BATUSDT     0.23050    0.23530    0.22970   
                          BCHUSDT   232.69000  234.49000  232.34000   
                          BNBUSDT    16.07600   16.33500   16.03500   
...                                       ...        ...        ...   
2024-01-16 16:00:00+00:00 YGGUSDT     0.56250    0.59140    0.55460   
                          ZECUSDT    23.44000   23.50000   23.06000   
                          ZENUSDT     8.74000    8.84900    8.51700   
                          ZILUSDT     0.02281    0.02334    0.02262   
                          ZRXUSDT     0.33880    0.34100    0.33580   

                                        Close        Volume        QuoVol  \
time                      symbol                                            
2020-06-21 00:00:00+00:00 ADAUSDT     0.07988  1.289528e+08  1.030266e+07   
                          ATOMUSDT    2.60000  2.186062e+05  5.718994e+05   
                          BATUSDT     0.23080  1.195930e+07  2.778131e+06   
                          BCHUSDT   233.27000  3.490217e+04  8.138722e+06   
                          BNBUSDT    16.04600  2.257289e+05  3.649726e+06   
...                                       ...           ...           ...   
2024-01-16 16:00:00+00:00 YGGUSDT     0.57590  3.073031e+07  1.765153e+07   
                          ZECUSDT    23.17000  1.609155e+05  3.745056e+06   
                          ZENUSDT     8.55200  6.329710e+05  5.502231e+06   
                          ZILUSDT     0.02295  4.221570e+08  9.680445e+06   
                          ZRXUSDT     0.33810  7.222316e+06  2.443316e+06   

                                      TrdCnt   TakerBuyVol  TakerBuyQuoVol  \
time                      symbol                                             
2020-06-21 00:00:00+00:00 ADAUSDT    20058.0  6.627875e+07    5.295948e+06   
                          ATOMUSDT    3455.0  9.524376e+04    2.493634e+05   
                          BATUSDT    11214.0  6.305698e+06    1.466296e+06   
                          BCHUSDT    14259.0  1.873830e+04    4.371109e+06   
                          BNBUSDT    17232.0  1.104412e+05    1.785496e+06   
...                                      ...           ...             ...   
2024-01-16 16:00:00+00:00 YGGUSDT   127955.0  1.511047e+07    8.677467e+06   
                          ZECUSDT    32139.0  8.289711e+04    1.929701e+06   
                          ZENUSDT    51664.0  2.687420e+05    2.336471e+06   
                          ZILUSDT    46410.0  2.066420e+08    4.740302e+06   
                          ZRXUSDT    23397.0  3.686560e+06    1.247178e+06   

                                    funding_rate  ...  avgtrdquo5  vwap_bias1  \
time                      symbol                  ...                           
2020-06-21 00:00:00+00:00 ADAUSDT      -0.000036  ...  479.795958    1.000185   
                          ATOMUSDT      0.000867  ...  160.740560    1.006199   
                          BATUSDT      -0.000584  ...  244.230070    1.006494   
                          BCHUSDT       0.000100  ...  463.688916    0.999643   
                          BNBUSDT       0.000223  ...  160.587017    1.007642   
...                                          ...  ...         ...         ...   
2024-01-16 16:00:00+00:00 YGGUSDT       0.000100  ...  143.354565    0.997398   
                          ZECUSDT       0.000100  ...  162.796265    1.004464   
                          ZENUSDT       0.000100  ...   90.929182    1.016453   
                          ZILUSDT       0.000100  ...  201.064744    0.999168   
                          ZRXUSDT       0.000100  ...  130.711339    1.000594   

                                    vwap_bias3

True