In [1]:
%load_ext autoreload
%autoreload 2

In [6]:
from gplearn.extra_functions_3 import *
import numpy as np

# Test ts_ER

In [4]:
x = np.array([[1.,2,3], [2,3,4], [3,4,5], [4,5,6]])
er = ts_ER(x, 2)
x, er

(array([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]]),
 array([[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan],
        [ 1.,  1.,  1.]]))

# Test ts_diff2nd

In [12]:
x = np.array([[1.,2,3], [2,3,4], [4,5,6], [7,8,9]])
diff2 = ts_diff2nd(x, 1)
np_diff2 = np.diff(x, 2, axis=0)
x, diff2, np_diff2

(array([[1., 2., 3.],
        [2., 3., 4.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 array([[nan, nan, nan],
        [nan, nan, nan],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))